name: CLARules
author: CLADevs Team
version: 1.1.0
description: An advanced rules plugin for PocketMine
main: CLARules\Main
api: 4.0.0
commands:
 rules:
  description: Rules command
  permission: rules.command
permissions:
 rules.command:
  default: true
