name: CLARules
author: CLADevs Team
version: 1.0.0
description: An advanced rules plugin for PocketMine
main: CLARules\Main
api: 3.0.0-ALPHA12
commands:
 rules:
  description: Rules command
  permission: rules.command
permissions:
 rules.command:
  default: true