# Variables:
#  - & for color coding
#  - {line} for a new line

# Options: book or message
rules-type: "book"

# Rules not found message
rules-not-found: "Rules not found."

# Book Config Options
rules-title: "Title"
rules-pages:
  - "Page 1"
  - "Page 2"
  - "Page 3"
  - "Page 4"
  - "Page 5"
  - "Page 6"
rules-author: "Author"
book-give-success-message: "Book has been given."
your-inventory-full: "Your inventory is full."

# Message Config Options
messages:
  - "Message 1"
  - "Message 2"
  - "Message 3"
  - "message 4"
  - "Message 5"
  - "Message 6"